### ISSUE TITLE
Make Dune parameters compatible with SQLFluff

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/onchain-analytics#26]
### Problem 1: SQLFluff is not run on files containing Dune parameters

https://github.com/sablier-labs/onchain-analytics/blob/99693f1e27e9beeef29e86ad4684c5b6bab25524/.sqlfluffignore#L1-L5

### Problem 2: Non-Standard Variable Names

Templating variables should never contain white spaces in the name. So a variable like `Start Date` should be named something like `start_date`. It's an anti-pattern that Dune allows this variable name in the first place.

cc @maxdesalle 

## Solution

Use the [Jinja templater](https://docs.sqlfluff.com/en/latest/configuration/templating/jinja.html#jinja-templater) feature of SQLFluff like so:

```toml
[sqlfluff]
templater = jinja

# Dummy values
[sqlfluff:templater:jinja:context]
addresses="0x0000000000000000000000000000000000000001,0x0000000000000000000000000000000000000002"
end_date="2025-01-01 00:00:00"
start_date="2025-01-01 00:00:00"
```

### Example

Turn this:

https://github.com/sablier-labs/onchain-analytics/blob/99693f1e27e9beeef29e86ad4684c5b6bab25524/queries/airdrops%3A_claim_count___4719750.sql#L10-L13

Into this:

```sql
WHERE
    contract_address IN ({{ addresses }})
    AND block_time > CAST('{{ start_date }}' AS TIMESTAMP)
    AND block_time < CAST('{{ end_date }}' AS TIMESTAMP)
```
